### ISSUE TITLE
Tutorial compare_with_external_photo

### ISSUE THREAD

**Issue by miguelglezb** [pykoala/koala#413]
Cannot unpack the output (tuple?) in argument `np.unravel_index(i, sampling[0].shape)` in:  
`sampling[:2, *np.unravel_index(i, sampling[0].shape)] = (`

Every cell after this fails because of this issue.

**Comment by PabloCorcho** [comment]
I could not fin any issue with the current version on main of this tutorial. Can you post which line of code is generating the error?

**Comment by miguelglezb** [comment]
This happens in the fourth cell and can be traced back to `pykoala/corrections/external_data.py` in line 107:

 ```sampling[:2, *np.unravel_index(i, sampling[0].shape)] = (
                 ^
SyntaxError: invalid syntax
```

**Comment by PabloCorcho** [comment]
If so, please close the issue :smile:

**Comment by miguelglezb** [comment]
Still having the same issue, even with the latest version of main:

```Traceback (most recent call last):

  File ~/koala/venv_koala/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3577 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[20],   [line 1](vscode-notebook-cell:?execution_count=20&line=1)
    from pykoala.corrections.external_data import AncillaryDataCorrection

  File ~/koala/venv_koala/lib/python3.10/site-packages/pykoala/corrections/external_data.py:107
    sampling[:2, *np.unravel_index(i, sampling[0].shape)] = (
                 ^
SyntaxError: invalid syntax
```

**Comment by PabloCorcho** [comment]
There was a compatibility issue between python3.11 and 3.10. I have fixed that in #425

**Comment by miguelglezb** [comment]
Notebook still failing but in fifth cell:

```
File ~/koala/venv_koala/lib/python3.10/site-packages/pykoala/corrections/external_data.py:387, in AncillaryDataCorrection.get_dc_aperture_fluxes(self, filter_names, dc_intensity_units, aperture_diameter, sample_every)
    [386](https://file+.vscode-resource.vscode-cdn.net/home/mbolivar/koala/tutorials/~/koala/venv_koala/lib/python3.10/site-packages/pykoala/corrections/external_data.py:386) try:
--> [387](https://file+.vscode-resource.vscode-cdn.net/home/mbolivar/koala/tutorials/~/koala/venv_koala/lib/python3.10/site-packages/pykoala/corrections/external_data.py:387)     from pst.observables import Filter
    [388](https://file+.vscode-resource.vscode-cdn.net/home/mbolivar/koala/tutorials/~/koala/venv_koala/lib/python3.10/site-packages/pykoala/corrections/external_data.py:388) except:

ModuleNotFoundError: No module named 'pst.observables'
``

**Comment by PabloCorcho** [comment]
Sorry Miguel, I missed that. That is a known issue. PST is a dependency of that particular correction and you haven't installed it. I will fix it once PST is on pypi. I am closing this issue and open a dedicated one for this.
